/* Undefine all field names (disable by setting VCAST_DO_NOT_UNDEF_FIELDS) */
#undef Is_Occupied
#undef Number_In_Party
#undef Designator
#undef Wait_Person
#undef Order
#undef Check_Total
#undef Soup
#undef Salad
#undef Entree
#undef Dessert
#undef Beverage
#undef v_false
#undef v_true
#undef NO_SOUP
#undef CHOWDER
#undef NO_SALAD
#undef GREEN
#undef NO_ENTREE
#undef PASTA
#undef NO_DESSERT
#undef FRUIT
#undef NO_BEVERAGE
#undef SODA
