
#ifndef VCAST_SBF_UNITS_AVAILABLE
#define VCAST_SBF_UNITS_AVAILABLE 
#endif
#ifdef VCAST_HAS_LONGLONG
#define VCAST_MIN_LONGEST_INT LLONG_MIN
#define VCAST_MAX_LONGEST_INT LLONG_MAX
#define VCAST_MAX_UNSIGNED_LONGEST_INT ULLONG_MAX
#else
#define VCAST_MIN_LONGEST_INT LONG_MIN
#define VCAST_MAX_LONGEST_INT LONG_MAX
#define VCAST_MAX_UNSIGNED_LONGEST_INT ULONG_MAX
#endif
