version: 2
updates:
  # Maven Dependencies for Jenkins Plugin - Target `tms_079`
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "tms_079"
    open-pull-requests-limit: 10
    commit-message:
      prefix: ""
    ignore:
      - dependency-name: "org.eclipse.collections:eclipse-collections"
        versions:
          - ">= 10.a"
      - dependency-name: "org.eclipse.collections:eclipse-collections-api"
        versions:
          - ">= 10.a"
      - dependency-name: "net.javacrumbs.json-unit:json-unit-assertj"
        versions:
          - ">= 3.0.0"

  # GitHub Actions - Still on master
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ""
