#
# The MIT License
#
# Copyright 2025 Vector Informatik, GmbH.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

import sys, os
from pprint import pprint
import argparse
import subprocess

from vcast_utils import checkVectorCASTVersion, dump, getVectorCASTEncoding

encFmt = getVectorCASTEncoding()

if not checkVectorCASTVersion(21, quiet = False):
    if __name__ != "__main__":
        raise ImportError("Full reports generated by previous call to generate-results.py")
    else:
        print("Full reports generated by previous call to generate-results.py")
        sys.exit(0)
        
else:
    from vector.apps.DataAPI.unit_test_api import UnitTestApi
    from vector.apps.DataAPI.vcproject_api import VCProjectApi

from vector.apps.DataAPI.cover_api import CoverApi

def dump(obj):
    if hasattr(obj, '__dict__'):
        return vars(obj)
    else:
        try:
            return {attr: getattr(obj, attr, None) for attr in obj.__slots__}
        except:
            return str(obj)

def generate_report(params):
    
    key, env_name, env_is_monitored, env_orig_env_dir, env_relative_wd, env_is_coverapi, env_is_ut_api, vcm_file, workspace, jenkins_workspace, VCD = params
    
    report_name = ""
    
    if env_is_monitored:
        build_dir = os.path.join(os.path.dirname(vcm_file), env_orig_env_dir)
        # print("Monitored: ", build_dir, env_name)
    else:
        build_dir = workspace + '/' + env_relative_wd
        # print("Migrated : ", build_dir, env_name)

    if len(key.split("/")) != 3:
        comp, ts, group, env_name = key.split("/")
    else:
        comp, ts, env_name = key.split("/")

    report_name = jenkins_workspace + "/management/" + comp + "_" + ts + "_" + env_name + ".html"

    try:
        cmd = ""

        if env_is_coverapi:
            cmd = VCD + "/clicast -e " + env_name + " COVER REPORT AGGREGATE " + report_name
            process = subprocess.Popen(cmd.split(), shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=build_dir)
            stdout, stderr = process.communicate()
            # print(cmd, stdout)
            result = process.returncode

        elif env_is_ut_api:
            cmd = VCD + "/clicast -e " + env_name + " REPORT CUSTOM FULL " + report_name
            process = subprocess.Popen(cmd.split(), shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=build_dir)
            stdout, stderr = process.communicate()
            # print(cmd, stdout)
            result = process.returncode

        else:
            return key, "Error: Cannot find the environment " + build_dir + "/" + env_name + ".vcp/.vce): " + cmd

        return key, stdout.strip()
    except Exception as e:
        import traceback
        return key, "Error: " + trackback.format_exc()

    return key, "Success: " + report_name + ": " + result

class RunFullReportsParallel(object):

    def __init__(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('ManageProject', help='VectorCAST Project Name')
        parser.add_argument('-j','--jobs', help='Number of concurrent jobs (default = maximun license count or processor)', default="max")
        parser.add_argument('--ci', help='Use Continuous Integration Licenses', action="store_true", default = False)
        parser.add_argument('-v', '--verbose', help='Enable verbose output', action="store_true", default = False)

        args = parser.parse_args()

        self.mpName = args.ManageProject
        self.verbose = args.verbose

        self.envDict = {}
        self.VCD = os.environ['VECTORCAST_DIR']

        try:
            self.jenkins_workspace = os.environ['CI_PROJECT_DIR'].replace("\\","/") + "/"
        except:
            try:
                self.jenkins_workspace = os.environ['WORKSPACE'].replace("\\","/") + "/"
            except:
                self.jenkins_workspace = os.getcwd().replace("\\","/") + "/"

        api = VCProjectApi(self.mpName)

        for env in api.Environment.all():
            if env.is_active:
                self.envDict[env.level._full_path] = env

        max_envs = len(api.Environment.all())
        
        self.variables = [(key, 
                    self.envDict[key].name, 
                    self.envDict[key].definition.is_monitored, 
                    self.envDict[key].definition.original_environment_directory,  
                    self.envDict[key].relative_working_directory,
                    isinstance(self.envDict[key].api,CoverApi),  
                    isinstance(self.envDict[key].api,UnitTestApi),
                    api.vcm_file, 
                    api.project.workspace, 
                    self.jenkins_workspace, 
                    self.VCD) 
                    for key in self.envDict.keys()]
        
        self.results = api.project.repository.get_full_status([])
        
        api.close()

        if args.jobs == "max":
            try:
                max_cpus = os.cpu_count()  # Python 3.4+
            except AttributeError:
                from multiprocessing import cpu_count as mp_cpu_count
                max_cpus = mp_cpu_count()  # Python 2.7 fallback
            max_licenses = self.getLicenseCount()
            
            print("Max CPUs    : {}".format(max_cpus))
            print("Max licenses: {}".format(max_licenses))
            print("Max Envs    : {}\n".format(max_envs))

            self.max_concurrent = min(x for x in [max_cpus,max_licenses, max_envs] if x > 0)

            print("Using licensing max = {}".format(self.max_concurrent))
        else:
            self.max_concurrent = int(args.jobs)


        self.info = []


        if args.ci:
            os.environ['VCAST_USE_CI_LICENSES'] = "1"

    def getLicenseCount(self, network=""):

        if os.environ.get("VECTOR_LICENSE_FILE") is not None:
            if sys.platform.startswith('win32'):
                cmd =  r'%VECTORCAST_DIR%\flexlm\lmutil lmstat -a -c %VECTOR_LICENSE_FILE% | findstr VECTORCAST_MANAGE:'
            else:
                cmd =  r'$VECTORCAST_DIR/flexlm/lmutil lmstat -a -c $VECTOR_LICENSE_FILE  | grep VECTORCAST_MANAGE:'

            process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = process.communicate()
            
            largest_available = 0
            
            if isinstance(stdout, bytes):
                stdout = stdout.decode(encFmt,'replace')
            
            for line in stdout.splitlines():
                if len(line) > 0:
                    total = line.split("Total of ")[1].split(" ")[0]
                    used  = line.split("Total of ")[2].split(" ")[0]
                    available = int(total) - int(used)
                    if available > largest_available:
                        largest_available = available

            return largest_available

        else:
            import xml.etree.ElementTree as ET
            from datetime import datetime
            import re
            
            if os.path.exists(r'C:\Program Files\Vector License Client\Vector.LicenseClient.exe'):
                cmd =  r'"C:\Program Files\Vector License Client\Vector.LicenseClient.exe" -listlicenses ' + network
            elif os.path.exists(r'C:\Program Files (x86)\Vector License Client\Vector.LicenseClient.exe'):
                cmd =  r'"C:\Program Files (x86)\Vector License Client\Vector.LicenseClient.exe" -listlicenses ' + network
            else:
                print("Cannot find the Vector License Client - setting license count to 1")
                return 1
                
            process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = process.communicate()
            
            if len(stderr) > 0:
                print("Error occurredn\{}\n{}".format(stdout,stderr))
                
            raw = stdout

            pattern = re.compile(b'encoding\\s*=\\s*"([^"]*)"')
            raw = pattern.sub(b'encoding="UTF-8"', raw, count=1)
            
            xml_data = raw.decode("utf-8", errors="replace")

            if self.verbose:
                print(xml_data)

            # Parse XML
            
            try:
                root = ET.fromstring(xml_data)
            except Eception as e:
                print("Exception in root = ET.fromstring(xml_data):", traceback.format_exc())
                return 1
                
            now = datetime.now()
            if os.environ.get("VCAST_USE_CI_LICENSES") is not None or os.environ.get("VCAST_USING_HEADLESS_MODE") is not None:
                searchType = ["Server Edition", "SE", "Server"]
            else:
                searchType = ["Desktop Edition", "DE", "Desktop"]

            free_list = []
            
            if root.findall('.//VectorLicense') == []:
                print("No Vector Licenses found locally, checking for network licenses")
                return self.getLicenseCount("-network")
                    
            # Loop through all VectorLicense nodes
            for lic in root.findall('.//VectorLicense'):
                product_text = lic.find('ProductText')
                expiration_text = lic.find('ExpirationDateString')
                free_licenses = lic.find('Quantity')

                if product_text is not None and expiration_text is not None and free_licenses is not None:
                    product = product_text.text.strip()
                    product_type = product_text.text.strip().split()[1]
                    expiration = expiration_text.text.strip()
                    free = int(free_licenses.text.strip())

                    if re.match(r'^VectorCAST.*', product):
                        exp_date = datetime.strptime(expiration, "%Y-%m-%dT%H:%M:%S")
                        if exp_date > now:
                            if product_type in searchType:
                                free_list.append(free)


            licMin = min(free_list) if free_list else 1
            return int(licMin)

        return 1

    def run(self):
        try:
            from  multiprocessing import Pool as mp_pool
            pool = mp_pool(processes=self.max_concurrent)
            results = pool.map(generate_report, self.variables)
        except UnboundLocalError as e:
            print("For some reason multiprocessing is regarded as a local variable")
            
        finally:
            pool.close()
            pool.join()
            # Optional: force cleanup before interpreter teardown
            from multiprocessing import util as mp_util
            mp_util._exit_function()

        for key, result in results:
            try:
                print("Completed: Full report for " + key)
            except Exception as e:
                import traceback
                print("Exception in {} : {}".format(key,traceback.format_exc()))

        print("All reports completed!")

if __name__ == "__main__":
    runner = RunFullReportsParallel()

    runner.run()
