-- VectorCAST 19.sp1 (06/26/19)
-- Test Case Script
-- 
-- Environment    : SIMPLE_ADA_TEST
-- Unit(s) Under Test: MANAGER
-- 
-- Script Features
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:ADA_DIRECT_ARRAY_INDEXING
--

-- Subprogram: <<INIT>>

-- Test Case: <<INIT>>.001
TEST.SUBPROGRAM:<<INIT>>
TEST.NEW
TEST.NAME:<<INIT>>.001
TEST.END

-- Unit: MANAGER

-- Subprogram: "&"

-- Test Case: &.001
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:"&"
TEST.NEW
TEST.NAME:&.001
TEST.VALUE:MANAGER."&".X:1
TEST.VALUE:MANAGER."&".Y:1
TEST.EXPECTED:MANAGER."&".return:1
TEST.END

-- Subprogram: "-"

-- Test Case: +.001
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:"-"
TEST.NEW
TEST.NAME:+.001
TEST.VALUE:MANAGER."-".X:1
TEST.VALUE:MANAGER."-".Y:2
TEST.EXPECTED:MANAGER."-".return:1
TEST.END

-- Subprogram: PLACE_ORDER

-- Test Case: PLACE_ORDER.Steak.BadCF
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.Steak.BadCF
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:1
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.FLOW
  MANAGER.PLACE_ORDER
  MANAGER.ADD_INCLUDED_DESSERT
  DATABASE.GET_TABLE_RECORD
  DATABASE.UPDATE_TABLE_RECORD
  MANAGER.PLACE_ORDER
TEST.END_FLOW
TEST.END

-- Test Case: PLACE_ORDER.Steak.BadEV
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.Steak.BadEV
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:1
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.CHECK_TOTAL:15
TEST.END

-- Test Case: PLACE_ORDER.Steak.CF
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.Steak.CF
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:1
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.FLOW
  MANAGER.PLACE_ORDER
  DATABASE.GET_TABLE_RECORD
  DATABASE.UPDATE_TABLE_RECORD
  MANAGER.PLACE_ORDER
TEST.END_FLOW
TEST.END

-- Test Case: PLACE_ORDER.Steak.EV
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.Steak.EV
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:1
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.EXPECTED:DATABASE.UPDATE_TABLE_RECORD.DATA.CHECK_TOTAL:14
TEST.END

-- Test Case: PLACE_ORDER.Steak.NoEV
TEST.UNIT:MANAGER
TEST.SUBPROGRAM:PLACE_ORDER
TEST.NEW
TEST.NAME:PLACE_ORDER.Steak.NoEV
TEST.VALUE:MANAGER.PLACE_ORDER.TABLE:1
TEST.VALUE:MANAGER.PLACE_ORDER.SEAT:1
TEST.VALUE:MANAGER.PLACE_ORDER.ORDER.ENTREE:STEAK
TEST.END

-- COMPOUND TESTS

TEST.SUBPROGRAM:<<COMPOUND>>
TEST.NEW
TEST.NAME:<<COMPOUND>>.001
TEST.SLOT: "1", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.EV"
TEST.SLOT: "2", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.NoEV"
TEST.SLOT: "3", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.CF"
TEST.SLOT: "4", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.BadEV"
TEST.SLOT: "5", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.BadCF"
TEST.END
--

-- COMPOUND TESTS

TEST.SUBPROGRAM:<<COMPOUND>>
TEST.NEW
TEST.NAME:<<COMPOUND>>.002
TEST.SLOT: "1", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.EV"
TEST.SLOT: "2", "MANAGER", "PLACE_ORDER", "1", "PLACE_ORDER.Steak.CF"
TEST.END
--
