name: Check for debug traces

on:
  pull_request:
    paths:
      - "src/main/resources/scripts/*.py"

jobs:
  import-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Import app .py files
      run: |
        cd src/main/resources/scripts
        echo "try:" > test.py
        echo "    import archive_extract_reports" >> test.py
        echo "    import cobertura" >> test.py
        echo "    import copy_build_dir " >> test.py
        echo "    import create_index_html " >> test.py
        echo "    import extract_build_dir " >> test.py
        echo "    import fixup_reports " >> test.py
        echo "    import full_report_no_toc " >> test.py
        echo "    import importlib " >> test.py
        echo "    generate_results = importlib.import_module(\"generate-results\") " >> test.py
        echo "    import generate_lcov " >> test.py
        echo "    import generate_pclp_reports " >> test.py
        echo "    import generate_qa_results_xml" >> test.py
        echo "    import generate_sonarqube_pclp_reports" >> test.py
        echo "    import generate_sonarqube_testresults" >> test.py
        echo "    import generate_xml" >> test.py
        echo "    import getjobs" >> test.py
        echo "    import incremental_build_report_aggregator" >> test.py
        echo "    import managewait" >> test.py
        echo "    import merge_vcr" >> test.py
        echo "    import parallel_full_reports" >> test.py
        echo "    import parse_console_for_cbt " >> test.py
        echo "    import parse_traceback " >> test.py
        echo "    import patch_rgw_directory " >> test.py
        echo "    import prevcast_parallel_build_execute " >> test.py
        echo "    import safe_open " >> test.py
        echo "    import tcmr2csv " >> test.py
        echo "    import tee_print " >> test.py
        echo "    import vcastcsv2jenkins " >> test.py
        echo "    import vcast_exec " >> test.py
        echo "    import vcast_utils " >> test.py
        echo except: >> test.py
        echo "    import sys  " >> test.py
        echo "    sys.exit(-1)  " >> test.py
        
        python3 test.py
