name: 'Java Lint'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest]
        jdk: [17]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }} with JDK ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.jdk }}'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build with Maven
        env:
          BROWSER: chrome-container
        run: mvn -V --color always -ntp clean compile -Plint --file pom.xml '-Djenkins.test.timeout=5000' '-Dgpg.skip'